package TQSProject.EatsDelivery.Selenium;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.HashMap;
import java.util.Map;

public class EatsTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.gecko.driver", "/home/passos/Downloads/firefox/geckodriver");
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void eats() {
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(1920, 1023));
        driver.findElement(By.id("us")).click();
        driver.findElement(By.linkText("Register")).click();
        driver.findElement(By.id("us")).click();
        driver.findElement(By.id("us")).sendKeys("Jorge Jesus");
        driver.findElement(By.id("psw")).sendKeys("vieiraout");
        driver.findElement(By.id("psw-repeat")).sendKeys("vieiraout");
        driver.findElement(By.cssSelector(".registerbtn")).click();
        driver.findElement(By.id("us")).click();
        driver.findElement(By.id("us")).sendKeys("Jorge Jesus");
        driver.findElement(By.id("psw")).sendKeys("vieiraout");
        driver.findElement(By.id("psw")).sendKeys(Keys.ENTER);
        /*driver.findElement(By.cssSelector("div:nth-child(1) > .col-md-3 button")).click();
        driver.findElement(By.cssSelector(".lnr-magnifier")).click();
        driver.findElement(By.id("product_keyword")).click();
        driver.findElement(By.id("product_keyword")).sendKeys("Big");
        driver.findElement(By.cssSelector(".input-group-addon > button")).click();
        driver.findElement(By.cssSelector("button:nth-child(2)")).click();

         */
    }
}