package Project.estafeta.Selenium;

// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.HashMap;
import java.util.Map;

public class EstafetasTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.gecko.driver", "/home/passos/Downloads/firefox/geckodriver");
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void estafetas() {
        driver.get("http://localhost:8080/api/courier");
        driver.manage().window().setSize(new Dimension(1920, 1023));
        driver.findElement(By.linkText("Register")).click();
        driver.findElement(By.cssSelector(".container:nth-child(1)")).click();
        driver.findElement(By.id("us")).click();
        driver.findElement(By.id("us")).sendKeys("Miguel Branco");
        driver.findElement(By.id("em")).sendKeys("ocnarb@gmail.com");
        driver.findElement(By.id("psw")).sendKeys("ocnarb");
        driver.findElement(By.id("psw-repeat")).sendKeys("ocnarb");
        driver.findElement(By.id("psw-repeat")).sendKeys(Keys.ENTER);
        driver.findElement(By.id("em")).click();
        driver.findElement(By.id("em")).sendKeys("ocnarb@gmail.com");
        driver.findElement(By.id("em")).sendKeys(Keys.ENTER);
        driver.findElement(By.id("psw")).sendKeys("ocnarb");
        driver.findElement(By.id("psw")).sendKeys(Keys.ENTER);
        /*driver.findElement(By.cssSelector("tr:nth-child(1) i")).click();
        driver.findElement(By.cssSelector("button:nth-child(3)")).click();
        driver.findElement(By.cssSelector("button")).click();

         */
    }
}
