# This is a basic workflow to help you get started with Actions

name: TQS Project CI/CD Pipeline 

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs static code analysis through SonarQube on courier app
      - name: Static Code Analysis on courier app
        run: mvn -f ./estafeta/pom.xml clean verify sonar:sonar -Dsonar.login=869414594979caa69b311d99b0227c4207e23358

      # Runs static code analysis through SonarQube on restaurant app
      - name: Static Code Analysis on restaurant app
        run: |
          mvn -f ./EatsDelivery/pom.xml clean verify sonar:sonar -Dsonar.login=869414594979caa69b311d99b0227c4207e23358
